### ISSUE TITLE
Add delete_protection to DynamoDB table

### ISSUE THREAD

**Issue by gw0** [cloudposse/terraform-aws-tfstate-backend#143]
### Describe the Feature

This TF module has a `force_destroy` variable that can prevent accidental S3 bucket deletions. The DynamoDB table also supports a similar flag `deletion_protection_enabled` that prevents accidental deletions.
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#deletion_protection_enabled

Because the purpose is the same, I would suggest reusing the variable also for this case by adding the following into the [aws_dynamodb_table](https://github.com/cloudposse/terraform-aws-tfstate-backend/blob/main/main.tf#L241):
```
deletion_protection_enabled = !var.force_destroy
```

### Expected Behavior

DynamoDB `deletion_protection_enabled` should also be enabled by default.

### Use Case

Prevent accidental deletions.

### Describe Ideal Solution

```
deletion_protection_enabled = !var.force_destroy
```

**Comment by simcomp2003** [comment]
Reporting same problem. 
If Dynamo table will not be destroyed some-were in middle of destroy but as last one, that will also work.

**Comment by osiris-mission** [comment]
Any update on this issue?  Run into a problem every time testing that the table gets deleted which also gets rid of the lock file.

**Comment by hans-d** [comment]
should be fixed.
