### ISSUE TITLE
invalid or unknown key: server_side_encryption

### ISSUE THREAD

**Issue by kitsunde** [cloudposse/terraform-aws-tfstate-backend#2]
```terraform
variable "region" {
  default = "ap-southeast-1"
}

provider "aws" {
  region = "${var.region}"
}

module "terraform_state_backend" {
  source = "git::https://github.com/cloudposse/terraform-aws-tfstate-backend.git?ref=master"
  namespace = "master"
  stage = "master"
  name = "mediapop"
  region = "${var.region}"
}
```

gives:

> Error: module.terraform_state_backend.aws_dynamodb_table.default: : invalid or unknown key: server_side_encryption

**Comment by aknysh** [comment]
@kitsunde 
thanks for testing!
what Terraform version are you using?
they just recently (in March) added DynamoDB server-side encryption to the AWS provider

https://github.com/terraform-providers/terraform-provider-aws/pull/3303
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1110-march-09-2018

can you update to the newest TF version and retest?

**Comment by kitsunde** [comment]
I’m using the latest available on macOS 0.11.5. It’s possible it’s because I’m trying to do it in SG, I switched to a different module.

________________________________

**Comment by kitsunde** [comment]
Ah, that was probably it. I was on 1.9.

**Comment by aknysh** [comment]
@kitsunde 
were you able to run it?
let us know if any other issues.

**Comment by osterman** [comment]
Will close this for now. Please reopen if you're still having trouble.
