### ISSUE TITLE
Bucket S3 Policy

### ISSUE THREAD

**Issue by pmayet** [cloudposse/terraform-aws-tfstate-backend#5]
Hi,

After first terraform apply the bucket S3 isn't created with the policy, so with the backend configuration and after the terraform init, with have this result : 

```
Error inspecting states in the "s3" backend:
    AccessDenied: Access Denied
	status code: 403, request id: 47E272D927CA9A6A, host id: P0C6vfjPgHasrSZ6sWGCQH4ZnFWdC0Ax7GNc2HdSX/+HWaHXqUbqgx+8I33pHS849KLTwhWyQik=
```

Best regards,

**Comment by aknysh** [comment]
@pmayet 
did you solve the issue?
thanks for testing!
