### ISSUE TITLE
Add missing GitHub Actions build badge

### ISSUE THREAD

**Issue by RothAndrew** [cloudposse/terraform-aws-tfstate-backend#50]
#49 does not include the new badge. It still needs to be added according to the [docs](https://docs.cloudposse.com/community/automated-testing/#chatops-configuration)

**Comment by osterman** [comment]
Ya, we're going to need to add something that builds on master. There's no easy way to get a build-badge with the chatops. Note, that it runs on `cloudposse/actions@master`` and not this repo so the status don't line up.

**Comment by nitrocode** [comment]
There is a release badge at the moment and it's updated when a new release is published after a PR is tested successfully and merged. I'll close for now. Please reopen if this is still an issue.
