### ISSUE TITLE
terraform destroy fails due to empty coalesce in output

### ISSUE THREAD

**Issue by schollii** [cloudposse/terraform-aws-tfstate-backend#51]
## Describe the Bug
Using terraform 0.12: 

1. create a main.tf that uses this module
2. terraform init and apply 
3. terraform destroy

eventually the following happens: 
```
$ terraform destroy
...
Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes


Error: Error in function call

  on .terraform/modules/terraform_state_backend/output.tf line 30, in output "dynamodb_table_id":
  30:     coalescelist(
  31: 
  32: 
  33: 
    |----------------
    | aws_dynamodb_table.with_server_side_encryption is empty tuple
    | aws_dynamodb_table.without_server_side_encryption is empty tuple

Call to function "coalescelist" failed: no non-null arguments.
```

## Expected Behavior
It should have finished properly. Looks like the coalesce is incorrect. 

## Fix
This is likely due to the new behavior of coalescelist() in terraform 0.12. 

Add `[""]` to the coalesclist() call. I will try to submit a PR.

**Comment by schollii** [comment]
So upon further thought, adding the empty string list is a hack for backwards compat with terraform 0.11, because the 0.12 coalescelist behavior is correct: the function returns the first non-empty list so if they are all empty, it does not make sense to return anything and it should raise an exception. 

The deeper issue is that terraform tries to render outputs as part of a destroy, which doesn't make sense in general and is likely to have other similar issues with undefined objects. See my comment https://github.com/hashicorp/terraform/issues/25390#issuecomment-649493926.

**Comment by nitrocode** [comment]
This issue seems resolved @schollii . If not, please comment the ticket again.

Thanks again for the contribution.
