### ISSUE TITLE
Make s3 bucket and dynamodb table optional

### ISSUE THREAD

**Issue by schollii** [cloudposse/terraform-aws-tfstate-backend#72]
## Describe the Feature

The module ("tatb") should support use case: use existing bucket but still create dynamodb table

I could refactor code from the module into my own module, but I'm asking here to avoid re-inventing the wheel if someone has already done this. 

## Use Case

Say we have 2 stacks (say `dev` and `staging`) with the state subdivided like this: 
```
s3://common_bucket
  stack_1 (dev)
    cluster.tfstate
    rds.tfstate (references cluster.tfstate as remote)
    app_1_deployment_1.tfstate (references rds.tfstate as remote)
    app_1_deployment_2.tfstate (references rds.tfstate as remote)
    app_2_deployment_1.tfstate (references cluster.tfstate as remote)
  stack_2 (staging)
    cluster.tfstate
    app_2_deployment_1.tfstate  (references cluster.tfstate as remote)
```
The above is managed by 6 terraform root modules: 
- each root module has its own backend.tf file referring to same bucket, but different key fore each
- all root modules that pertain to stack 1 use the same dynamodb lock table, and same goes for stack 2

It would be nice to use terraform-aws-tfstate-backend module in each of those root modules, but this is not possible because it enforces s3 bucket creation and dynamo-db table creation. 

Hence the feature request listed at the top. 

## Describe Ideal Solution

Basically make the bucket creation optional when using the module. 

With that capability, one could have the bucket created by a separate root module that uses the tatb module, with these properties: 

| root module              | create bucket | create lock table |
|--------------------------|---------------|-------------------|
| all-states bucket            | y             | y                 |
| cluster 1                | n             | y                 |
| cluster 2                | n             | y                 |
| other modules in stack 1 | n             | n                 |
| other modules in stack 2 | n             | n                 |

namely:
- the first row is "use the tatb module as-it-is-now"; 
- the last 2 rows are "use the backend.tf directly"; 
- the use-case "create bucket but not dynamodb table" does not exist IMO

so the 2 cluster rows are the only ones that really new a patch: sufficient to add a new "existing_state_bucket" variable that causes use of existing bucket but still creates the dynamodb table.

**Comment by osterman** [comment]
I think we can consider adding a feature flag (E.g. `bucket_enabled` and default it to `true`, and `dynamodb_enabled` and default it to `true`). Would satisfy your requirements? While I don't think _we'll_ implement it, we would accept the PR.

**Comment by schollii** [comment]
Yes that would work I will submit something

**Comment by pjanuario** [comment]
FYI - I have a similar need, this would prevent the need to have a resource per each stack.
I will look into it if I can make the PR.

**Comment by schollii** [comment]
Yes please do just have not had time
