### ISSUE TITLE
DynamoDB label attributes inconsistent due to null label module

### ISSUE THREAD

**Issue by Xerkus** [cloudposse/terraform-aws-tfstate-backend#91]
## Describe the Bug

Label created for DynamoDB is different depending on how `attributes` was passed to this module: as variable or in context

Moving `attributes` to context results in this plan (unrelated changes snipped):

```hcl
-/+ resource "aws_dynamodb_table" "with_server_side_encryption" {
      ~ id               = "eg-terraform-state-lock" -> (known after apply)
      ~ name             = "eg-terraform-state-lock" -> "eg-terraform-lock-state" # forces replacementd
      ~ tags             = {
          ~ "Attributes" = "state-lock" -> "lock-state"
          ~ "Name"       = "eg-terraform-state-lock" -> "eg-terraform-lock-state"
            # (1 unchanged element hidden)
        }
      ~ tags_all         = {
          ~ "Attributes" = "state-lock" -> "lock-state"
          ~ "Name"       = "eg-terraform-state-lock" -> "eg-terraform-lock-state"
            # (1 unchanged element hidden)
        }
```

Seems to be related to cloudposse/terraform-null-label#114 which was released in `0.22.1` while this module pins  to `0.22.0`

## Expected Behavior

`dynamodb_table_label` should have same order regardless of how attributes were passed.

Assuming suggested README usage producing desirable result (`concat(context, var, ["state"]`), label module can be bumped to 0.22.1 or newer

## Steps to Reproduce

1. Setup module as suggested in README
2. Run plan and make note of DynamoDB table resource, particularly id, name and tags
3. Move attributes variable to context object
4. Run plan again and compare DynamoDB values 

## Environment (please complete the following information):
```
$ terraform version
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

$ terraform get -update
Downloading cloudposse/tfstate-backend/aws 0.33.0 for terraform_state_backend...
- terraform_state_backend in .terraform/modules/terraform_state_backend
Downloading cloudposse/label/null 0.22.0 for terraform_state_backend.dynamodb_table_label...
- terraform_state_backend.dynamodb_table_label in .terraform/modules/terraform_state_backend.dynamodb_table_label
Downloading cloudposse/label/null 0.24.1 for terraform_state_backend.this...
- terraform_state_backend.this in .terraform/modules/terraform_state_backend.this
```

## Additional Context

This module is likely to be used in root module and combined with README instructions this issue is unlikely affect many

**Comment by Gowiem** [comment]
@Xerkus the latest version of this module pins `v0.24.1` of terraform-null-label. Could your issue be that you're pinned to an older version? Latest is `0.33.0`.

**Comment by Xerkus** [comment]
`terraform get` in the log above shows 0.33.0

It still uses 0.22.0 in default branch, here:
https://github.com/cloudposse/terraform-aws-tfstate-backend/blob/793d3f90c25d9f17f4a299be7b13ae5141795345/main.tf#L164-L169
